export const ICONS_TEXTS = {
  battery_full: "",
  clock: "",
  calendar: "",
  disk: "",
  loading: "",
  volume_high: "",
  cpu: "",
  memory: "",
  coffee_on: "󰅶",
  coffee_off: "󰶞",
  config: "",
  weather: "󰖙",
  save: "",
  exit: "󰩈",
  Appearance: "",
  Widgets: "󰜬",
  Advanced: "󰏙",
  info: "󰋼",
  error: "",
  success: "",
  warning: "",
  box: "󱓻",
  check: "",
} as const;

export type IconName = keyof typeof ICONS_TEXTS;
